### ISSUE TITLE
Compiled in more recent version of java

### ISSUE THREAD

**Issue by SuxAsLux** [Zsongli/quick-stack#1]
Hi!
Im trying to use your plugin on my paper home server but i get this error when im starting the server.
Im using paper 1.21.1 and 1.21.1 client in offline mode.
My java version is: `"17.0.9" 2023-10-17 LTS`

Could you please compile it in an earlier version of java?

Here is the error:
`[11:31:26 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'QuickStack.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: li/zsong/quickstack/Plugin has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0`

Thanks in advance!

**Comment by Zsongli** [comment]
Hi, I've updated the latest release with the recompiled version. Try downloading it again.
If you still have the issue, I recommend that you download the source code and try to compile it yourself.

Merry Christmas!

**Comment by SuxAsLux** [comment]
It works like a charm!
Thanks!

Merry Christmas to you as well!
